### ISSUE TITLE
j.modular crashes when receive (protocol/setup port 9998) message

### ISSUE THREAD

**Issue by bltzr** [jamoma/JamomaPureData#14]
as reported in https://gist.github.com/bltzr/92cd9bee40ab3d531807
j.modular crashes when creating a Minuit device

**Comment by avilleret** [comment]
afaik, the crash is triggered by sending `[protocol/setup port 9998(` message to `[j.modular]`.
and this happens with git rev c11b97a cross compiled on Ubuntu.

**Comment by bltzr** [comment]
I also had a crash with the i-score_remote example
not sure it's related, though
log: https://gist.github.com/bltzr/a3c19838f4210efb1737

**Comment by theod** [comment]
unfortunatelly I can't reproduce the crash on Mac OS but in the same time it seems i-score can't explore the pure data patcher so I'm not sure j.modular is working...

**Comment by bltzr** [comment]
I had this happening on raspbian

**Comment by avilleret** [comment]
I proud to annonce that j.modular is now working on RPi and thus websocket and i-score remote are working too

**Comment by theod** [comment]
wouah ! congratulation @avilleret !

**Comment by reno-** [comment]
Whaou !!!!
What version of raspbian is needed? wheezy, jessie or both?

**Comment by avilleret** [comment]
I've done it under jessie with a native build.
We could test on Wheezy.
And we should check if nightly build are working.

## 

do it yourself
http://antoine.villeret.free.fr

2015-10-16 15:58 GMT+02:00 Renaud notifications@github.com:

**Comment by bltzr** [comment]
:heart: :heart: :heart: 
:sunglasses:
