### ISSUE TITLE
j.remote crashes pd when bound

### ISSUE THREAD

**Issue by bltzr** [jamoma/JamomaPureData#19]
apparently, j.remote crashes pd when it is given an "existing" address to bind to

demonstrated with patcher below (using relative adresses):
# N canvas 717 508 450 300 10;
# X obj 59 97 j.model;
# X obj 240 143 j.parameter toto;
# X obj 59 145 print;
# X floatatom 199 142 5 0 0 0 - - -, f 5;
# X floatatom 181 204 5 0 0 0 - - -, f 5;
# X obj 222 205 j.remote toto;
# X connect 0 0 2 0;
# X connect 1 0 3 0;
# X connect 3 0 1 0;
# X connect 4 0 5 0;
# X connect 5 0 4 0;

naming this "test.model.pd" and opening this also crashes (with absolute addresses):
# N canvas 628 28 450 300 10;
# X floatatom 76 164 5 0 0 0 - - -, f 5;
# X floatatom 92 132 5 0 0 0 - - -, f 5;
# X obj 90 62 test.model /test.1;
# X obj 215 61 test.model /test.2;
# X obj 117 164 j.cremote /test.1/toto;
# X obj 132 133 j.remote /test.2/toto;
# X connect 0 0 4 0;
# X connect 1 0 5 0;
# X connect 4 0 0 0;
# X connect 5 0 1 0;

**Comment by avilleret** [comment]
could you try again with the nighlty builds from last night ?
https://github.com/jamoma/nightly-builds/blob/master/JamomaPuredata/JamomaPd-OSX-fat_binary.tar.gz

I remove some uneeded lib and also review the j.remote output mechanism

**Comment by avilleret** [comment]
I can't reproduce this so I close the ticket
