### ISSUE TITLE
Build on Mac OS X fails

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaPureData#2]
building on Mac OS with CMake fails with `error: symbol(s) not found for architecture x86_64`
see : https://gist.github.com/avilleret/20c3a94c454d131d7ccc

googling the issue point me to a libstdc++ issue, Puredata might have been build with another lib than Jamoma, but I don't understand where it knows something about that since PD is just header without linking lib (at compile time).
The only lib that need to be link to is the CicmWrapper which is build with CMake too (so I guess with the some settings)

**Comment by jcelerier** [comment]
By the looks of it, it might require the same stuff that Max does (cf. https://github.com/jamoma/JamomaCore/blob/dev/Shared/CMake/JamomaUtilFunctions.cmake:272). 

So for instance : 

```
set(PD_SYM_LINKER_FLAGS " -Wl,-U,_atom_getfloat,-U,_atom_getint,...")

# Pick the one that relates to how Pd externals are built
# if add_executable
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${PD_SYM_LINKER_FLAGS}" PARENT_SCOPE)
# if add_library(... SHARED ...); (I think it is the default case, hence also when SHARED is not presenter)
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${PD_SYM_LINKER_FLAGS}" PARENT_SCOPE)
# if add_module
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${PD_SYM_LINKER_FLAGS}" PARENT_SCOPE)
```

**Comment by avilleret** [comment]
I saw that and I've already tried that at least for some of the symbols without any success for now, 
I may persevere in that direction
