### ISSUE TITLE
j.cue crash when receive [write cue_list.txt(

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaPureData#29]
as reported by @steevebrush, Pd 0.46-7 crashes on Mac OS X (10.10 and 10.11) when sending `[write(` message to `[j.cue]`

it doesn't crash on Ubuntu 15.10 with Pd 0.46-7.

**Comment by steevebrush** [comment]
the file is written on disk and seems to be ok, the crash occurs after.
Pd crashes too when reading the cue file from disk after selecting it.

**Comment by avilleret** [comment]
here is a backtrace for the record https://gist.github.com/avilleret/d444a4b111d086c5a21f

**Comment by avilleret** [comment]
@steevebrush could you the next build ?
https://travis-ci.org/jamoma/JamomaPureData/jobs/95647736
but please wait a little bit ;-)

**Comment by steevebrush** [comment]
no luck with a330343, tried Pd-0.46-7 both 32 an 64 bits version.

**Comment by steevebrush** [comment]
c1a9967 works ! :thumbsup:
