### ISSUE TITLE
cmake fails on osx

### ISSUE THREAD

**Issue by reno-** [jamoma/JamomaPureData#4]
I follow the instructions on the readme (dev branch) but cmake gave me errors.
Here is the terminal output : 
https://gist.github.com/reno-/d1622b3fd82b7232b3d3
Here is the cmake log :
https://gist.github.com/reno-/65ab8fd98dda2207e764

**Comment by avilleret** [comment]
could you try again folowing the changes I made in 63b7c8a ?

you are probably missing some things specific to Mac OS X that are not needed on Ubuntu

**Comment by reno-** [comment]
Ok, nice ! But I still have a warning at the end of cmake : 
>CMake Warning:  Manually-specified variables were not used by the project:
 > BUILD_JAMOMAPD
  >-- Build files have been written to: /Users/reno/Documents/GITs/Jamoma4PD/Implementations/PureData/build

but it now fails with [make]
>4 warnings generated.
Linking CXX shared library ../libJamomaPd.dylib
ld: library not found for -lFoundation
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libJamomaPd.dylib] Error 1
make[1]: *** [library/CMakeFiles/JamomaPd.dir/all] Error 2
make: *** [all] Error 2

Here is my total log
https://gist.github.com/reno-/326e208ebdca4501dafd

**Comment by reno-** [comment]
nice it works !!
wouhou !!
