### ISSUE TITLE
Pd crash when loading Jamoma

### ISSUE THREAD

**Issue by reno-** [jamoma/JamomaPureData#7]
I tried to build JamomaPureData on OSX (OS10.10.3) but Pure Data crashs on loading.

Maybe someone knows what happens?

> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   dyld                            0x00007fff6d9a8075 dyld_fatal_error + 1
> 1   dyld                            0x00007fff6d9ab241 dyld::fastBindLazySymbol(ImageLoader*_, unsigned long) + 180
> 2   libdyld.dylib                   0x00007fff9afc33ba dyld_stub_binder + 282
> 3   ???                             0x0000000106f8f008 0 + 4411944968
> 4   libJamomaFoundation.6.dylib     0x0000000104e1c9ca bool TTLoadExtension<TTOSXSpecific, bool TTUnixCommon::TTLoadExtensionsFromFolder<TTOSXSpecific>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(char const_), bool TTUnixCommon::TTLoadExtensionsFromFolder<TTOSXSpecific>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(void_, char const_)>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool TTUnixCommon::TTLoadExtensionsFromFolder<TTOSXSpecific>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(char const_)&&, bool TTUnixCommon::TTLoadExtensionsFromFolder<TTOSXSpecific>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(void_, char const_)&&) + 602 (TTExtensionLoader.cpp:109)
> 5   libJamomaFoundation.6.dylib     0x0000000104e1c6e0 bool TTUnixCommon::TTLoadExtensionsFromFolder<TTOSXSpecific>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 128 (TTExtensionLoader.cpp:167)
> 6   libJamomaFoundation.6.dylib     0x0000000104e1c008 bool TTLoadExtensionsFromBuiltinPaths<TTOSXSpecific>() + 152 (algorithm:878)
> 7   libJamomaFoundation.6.dylib     0x0000000104e1be8b TTLoadExtensions(char const_, bool) + 235 (TTExtensionLoader.cpp:459)
> 8   libJamomaModular.6.dylib        0x0000000104d025e4 TTModularInit(char const*, bool) + 20 (TTModular.cpp:48)
> 9   libJamomaPd.dylib               0x0000000104885fba jamoma_init() + 186 (TTSymbol.h:42)
> 10  jamoma.pd_darwin                0x00000001001dfa5d jamoma_setup + 13 (j.loader.cpp:142)

Here is the complete log
https://gist.github.com/reno-/e143e730f629ade019ad

**Comment by avilleret** [comment]
it seems that when extension are not loaded Jamoma loads but Pd crash when creating an object (see and #8 and #9)
and when it tries to load extension, it crashes too...

**Comment by reno-** [comment]
I tried with another computer with same OS (OS10.10.3), and I have the same behavior (crash with the same log)

**Comment by reno-** [comment]
> Exception Type:        EXC_BREAKPOINT (SIGTRAP)
> Exception Codes:       0x0000000000000002, 0x0000000000000000
> 
> Dyld Error Message:
>   Symbol not found: __Z16TTFoundationInitPKc
>   Referenced from: /usr/local/jamoma/extensions/DataspaceLib.ttdylib
>   Expected in: /Users/USER/Documents/*/libJamomaFoundation.6.dylib
> 
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   dyld                            0x00007fff6871b075 dyld_fatal_error + 1
> 1   dyld                            0x00007fff6871e241 dyld::fastBindLazySymbol(ImageLoader*_, unsigned long) + 180
> 2   libdyld.dylib                   0x00007fff95efa3ba dyld_stub_binder + 282
> 3   ???                             0x0000000105778008 0 + 4386684936
> 4   libJamomaFoundation.6.dylib     0x000000010556b99a bool TTLoadExtension<TTOSXSpecific, bool TTUnixCommon::TTLoadExtensionsFromFolder<TTOSXSpecific>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(char const_), bool TTUnixCommon::TTLoadExtensionsFromFolder<TTOSXSpecific>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(void_, char const_)>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool TTUnixCommon::TTLoadExtensionsFromFolder<TTOSXSpecific>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(char const_)&&, bool TTUnixCommon::TTLoadExtensionsFromFolder<TTOSXSpecific>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(void_, char const_)&&) + 602 (TTExtensionLoader.cpp:109)
> 5   libJamomaFoundation.6.dylib     0x000000010556b6b0 bool TTUnixCommon::TTLoadExtensionsFromFolder<TTOSXSpecific>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 128 (TTExtensionLoader.cpp:167)
> 6   libJamomaFoundation.6.dylib     0x000000010556afd8 bool TTLoadExtensionsFromBuiltinPaths<TTOSXSpecific>() + 152 (algorithm:878)
> 7   libJamomaFoundation.6.dylib     0x000000010556ae5b TTLoadExtensions(char const_, bool) + 235 (TTExtensionLoader.cpp:459)
> 8   libJamomaModular.6.dylib        0x00000001054515e4 TTModularInit(char const*, bool) + 20 (TTModular.cpp:48)
> 9   libJamomaPd.dylib               0x0000000103b0efba jamoma_init() + 186 (TTSymbol.h:42)
> 10  jamoma.pd_darwin                0x00000001001e8a5d jamoma_setup + 13 (j.loader.cpp:142)
> 11  pd                              0x000000010004e56a sys_do_load_lib + 954
> 12  pd                              0x000000010004e02a sys_load_lib + 58
> 13  pd                              0x000000010003e6eb new_anything + 107
> 14  pd                              0x000000010003e906 pd_typedmess + 118
> 15  pd                              0x00000001000422c1 binbuf_eval + 1041
> 16  pd                              0x0000000100008b2a canvas_objtext + 90
> 17  pd                              0x000000010000ad23 text_setto + 243
> 18  pd                              0x0000000100020667 glist_deselect + 375
> 19  pd                              0x0000000100022310 canvas_doclick + 1568
> 20  pd                              0x000000010003ebcb pd_typedmess + 827
> 21  pd                              0x000000010003e906 pd_typedmess + 118
> 22  pd                              0x00000001000422c1 binbuf_eval + 1041
> 23  pd                              0x000000010004a841 socketreceiver_read + 657
> 24  pd                              0x000000010004a287 sys_domicrosleep + 359
> 25  pd                              0x0000000100047904 m_mainloop + 1572
> 26  pd                              0x00000001000489cd sys_main + 1773
> 27  pd                              0x00000001000018dd _start + 203
> 28  pd                              0x0000000100001811 start + 33

**Comment by avilleret** [comment]
fix with https://github.com/jamoma/JamomaPureData/commit/b198574aa736edfede8ddb911132b46473bbd917
