### ISSUE TITLE
pd crash when instantiating a j.parameter

### ISSUE THREAD

**Issue by reno-** [jamoma/JamomaPureData#8]
OSX.9.5 - Pure Data vanilla 0.46.6 64 Bits

make a new patcher
make a [j.parameter test]
=> crash

> Crashed Thread:  0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000000
> 
> VM Regions Near 0:
> --> 
>     __TEXT                 0000000100000000-00000001000cb000 [  812K] r-x/rwx SM=COW  /Applications/Pd-0.46-6-64bit.app/Contents/Resources/bin/pd
> 
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   j.parameter.pd_darwin           0x000000010184727a wrapTTModularClassAsPdClass(TTSymbol&, char const_, _wrappedClass__, _modularSpecificities_) + 1610 (TTModularClassWrapperPd.cpp:875)
> 1   pd                              0x000000010004e56a sys_do_load_lib + 954
> 2   pd                              0x000000010004e02a sys_load_lib + 58
> 3   pd                              0x000000010003e6eb new_anything + 107
> 4   pd                              0x000000010003e906 pd_typedmess + 118
> 5   pd                              0x00000001000422c1 binbuf_eval + 1041
> 6   pd                              0x0000000100008b2a canvas_objtext + 90
> 7   pd                              0x000000010000ad23 text_setto + 243
> 8   pd                              0x0000000100020667 glist_deselect + 375
> 9   pd                              0x0000000100022310 canvas_doclick + 1568
> 10  pd                              0x000000010003ebcb pd_typedmess + 827
> 11  pd                              0x000000010003e906 pd_typedmess + 118
> 12  pd                              0x00000001000422c1 binbuf_eval + 1041
> 13  pd                              0x000000010004a841 socketreceiver_read + 657
> 14  pd                              0x000000010004a287 sys_domicrosleep + 359
> 15  pd                              0x0000000100047904 m_mainloop + 1572
> 16  pd                              0x00000001000489cd sys_main + 1773
> 17  pd                              0x00000001000018dd _start + 203
> 18  pd                              0x0000000100001811 start + 33

**Comment by avilleret** [comment]
may be related to #9
